application: mail-tag-reduce
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  script: main.py
  login: required
- url: /imapoauth_.*
  script: imapoauth.py
  
- url: /(google(.*).html)
  static_files: site-verif/\1
  upload: site-verif/(google(.*).html)

